development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: P@ssword1

test:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  timeout: 5000